// <auto-generated />
namespace MovieShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updateNameofCrewCast : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateNameofCrewCast));
        
        string IMigrationMetadata.Id
        {
            get { return "202002211355472_updateNameofCrewCast"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
